/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ArticleManage: typeof import("./components/ArticleManage.vue")["default"];
    CommentManage: typeof import("./components/CommentManage.vue")["default"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    UserCenter: typeof import("./components/UserCenter.vue")["default"];
    UserHome: typeof import("./components/UserHome.vue")["default"];
    UserManage: typeof import("./components/UserManage.vue")["default"];
  }
}
